name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: mkdir TestArtifact
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install newman
        run: |
          npm install -g newman@5.3.0
          npm install -g newman-reporter-slackreporter@1.0.0
          npm install -g newman-reporter-htmlextra@1.5.4
      - name: Run Tests
        id: test
        run: |
          newman run "PostManTests/GitHubActionsTest.postman_collection.json" -e "PostManTests/GitHubActionsTest.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export TestArtifact/htmlreport.html || exit 1
      - name: Publish Report 
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: TestArtifact
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        if: ${{ success() }}
        run: mvn clean install
